//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

pub mod prelude;

pub mod global_materials;
pub mod global_recipes;
pub mod unit_bases;
pub mod unit_categories;
pub mod units;
pub mod users;
